# app_login:
#    path: '/login'
#    controller: 'App\Controller\LoginController::login'

# app_home_front:
#    path: '/front'
#    controller: 'App\Controller\HomeController::front'

# app_home_back:
#    path: '/back'
#    controller: 'App\Controller\HomeController::back'


