#index:
#    path: /
#    controller: App\Controller\DefaultController::index
modifier_utilisateur:
  path: '/utilisateur/modifier/{id}'
  controller: 'App\Controller\UtilisateursController::modifier'
  methods: ['GET', 'POST']

app_utilisateurs_display:
  path: '/utilisateur/{id}'
  controller: 'App\Controller\UtilisateursController::display'
  methods: ['GET']

generate_sports_pdf:
  path: listS
  controller:  App\Controller\PdfController::pdf
  #  Tri nom asc
terrain_display_sorted_by_nom_asc:
    path: '/tri/sorted_by_nom_asc'
    controller: App\Controller\TriController::displaySortedByNomASC

#  Tri type asc
terrain_display_sorted_by_sport_asc:
    path: '/tri/sorted_by_sport_asc'
    controller: App\Controller\TriController::displaySortedBySportASC
#  Tri nom desc
terrain_display_sorted_by_nom_desc:
    path: '/tri/sorted_by_nom_desc'
    controller: App\Controller\TriController::displaySortedByNomDESC

#  Tri type desc
terrain_display_sorted_by_sport_desc:
    path: '/tri/sorted_by_sport_desc'
    controller: App\Controller\TriController::displaySortedBySportDESC




add_to_cart:
    path: '/shop/add_to_cart/{productId}'
    controller: 'App\Controller\ShopController::addToCart'
    methods: ['GET', 'POST']

